platform :ios,'8.0'
target “FindWorkerApp” do
use_frameworks!
pod 'AFNetworking','~> 3.1.0'
pod 'MBProgressHUD', '~> 0.8'
pod 'SDWebImage', '~> 3.7.2'
pod 'MONActivityIndicatorView', '~> 0.0.3'
pod 'Masonry'
pod 'BaiduMapKit’,’~> 3.4.0’
pod 'RongCloudIM/IMLib', '~> 2.8.3'
pod 'RongCloudIM/IMKit', '~> 2.8.3'
pod 'JPush','3.0.6'
pod 'Qiniu', '~> 7.1'
pod 'FMDB'
end

